# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_puppet = <<-PUPPET
sudo apt-get update -y
sudo apt-get install -y puppet
PUPPET

Vagrant.configure("2") do |config|

  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

 config.vm.define :servidor do |servidor|
 servidor.vm.box = "bento/ubuntu-22.04"
 servidor.vm.network :private_network, ip: "192.168.50.3" 
 servidor.vm.hostname = "servidor"
 servidor.vm.provision "shell", path: "script.sh"
 servidor.vm.synced_folder "C:/Users/apala/OneDrive/Documents/Sincronizado", "/home/vagrant/sincrono"
 end

 config.vm.define :cliente do |cliente|
 cliente.vm.box = "bento/ubuntu-22.04"
 cliente.vm.network :private_network, ip: "192.168.50.2"
 cliente.vm.hostname = "cliente"
 end

 config.vm.define :puppetServer do |puppetServer|
    puppetServer.vm.box = "bento/ubuntu-20.04"
    puppetServer.vm.hostname = "puppetServer"
    puppetServer.vm.network :private_network, ip: "192.168.90.3"

    puppetServer.vm.provision "shell", inline: $install_puppet
 end
end
