# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.auto_update = false
    config.vbguest.no_remote   = true
  end

  config.vm.define :servidorWeb do |servidorWeb|
    servidorWeb.vm.box = "bento/ubuntu-22.04"
    servidorWeb.vm.network :private_network, ip: "192.168.80.3"
    servidorWeb.vm.hostname = "servidorWeb"
    servidorWeb.vm.provision "shell", path: "script.sh"
  end
end
